# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build auth-api image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/auth-api/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build todos-api image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/todos-api/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build users-api image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/users-api/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build log-message-processor image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/log-message-processor/Dockerfile'
        tags: |
          $(tag)
    