# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name : Docker-CI
trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'frontend' 
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build frontend image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'amsf9619/frontend'
        command: 'build'
        imageName: $(ImageName)
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: 'Push the Frontend Docker image to Dockerhub'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'amsf9619/frontend'
        command: 'push'
        imageName: $(ImageName)
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 
