apiVersion: v1
kind: Pod
metadata:
  name: auth-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: microservice-app-example
    spec:
      containers:
        name: auth
        image: amsf9619/auth:148
