apiVersion: v1
kind: pod
metadata:
  name: auth-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: auth-api
    spec:
      containers:       
        image: auth
        name: auth

